name = "agora"
main = "worker/src/index.js"
compatibility_date = "2026-04-19"

[[d1_databases]]
binding = "db"
database_name = "agora-db"
database_id = "6b9ceef1-9630-444b-9957-7a986e50914c"

[env.production]
name = "agora-prod"
route = "api/*"

[env.staging]
name = "agora-staging"
route = "api-staging/*"
