name = "agora"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "agora-db"
database_id = "6b9ceef1-9630-444b-9957-7a986e50914c"

[[kv_namespaces]]
binding = "KV"
id = "760f0c8734234d6a88ccd7cded5fa4fa"
